apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ngnix-deployment2
  name: ngnix-deployment2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngnix-deployment2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ngnix-deployment2
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
