apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  containers:
     - image: nginx 
     name: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "5400Mi"
        cpu: "0.5"
    requests:
        memory: "4400Mi"
        cpu: "0.3"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
