apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx_giropops
    name: nginx_giropops
spec:
  containers:
  - name: nginx_giropops
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "5400Mi"
        cpu: "0.5"
    requests:
        memory: "4400Mi"
        cpu: "0.3"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
