apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-giropops
    app: giropops-strigus
  name: nginx-giropops
spec:
  containers:
  - image: nginx 
    name: nginx-giropops 
    ports:
      - containerPort: 80      
    resources:
      limits:
        cpu: "0.5"
        memory: "5500Mi"
      requests:
        cpu: "0.3"
        memory: "4400Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
